# Generated by Django 5.0.4 on 2024-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_employee_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
