# Generated by Django 5.0.3 on 2024-03-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_assetallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('return_date', models.DateField()),
                ('asset_status', models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('damaged', 'Damaged')], max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('employee_returning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.employee')),
            ],
        ),
    ]
