# Generated by Django 5.0.3 on 2024-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_assetreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
