# Generated by Django 5.0.4 on 2024-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(blank=True, choices=[('2007', '2007'), ('2010', '2010'), ('2013', '2013'), ('2016', '2016'), ('365', '365')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office_licence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, choices=[('win7', 'Win7'), ('win8.1', 'Win8.1'), ('win10', 'Win10'), ('win11', 'Win11')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_licence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('server', 'Server'), ('printer', 'Printer'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
