# Generated by Django 5.0.4 on 2024-04-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_asset_ip_alter_asset_model_alter_asset_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset.company'),
        ),
    ]
