# Generated by Django 5.0.3 on 2024-03-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_assetallocation_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
