# Generated by Django 5.0.3 on 2024-03-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_asset_is_allocated_asset_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturn',
            name='employee_returning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.employee'),
        ),
    ]
