# Generated by Django 5.0 on 2024-05-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_asset_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
