# Generated by Django 5.0.3 on 2024-04-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_disposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset', to_field='name'),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='employee_allocated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.employee', to_field='first_name'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset', to_field='name'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='employee_returning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.employee', to_field='first_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
