# Generated by Django 5.0 on 2024-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_remove_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetallocation',
            name='serial_number',
        ),
    ]
