# Generated by Django 5.0 on 2024-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_remove_assetallocation_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetreturn',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('server', 'Server'), ('printer', 'Printer'), ('tablet', 'Tablet'), ('UPS', 'UPS'), ('Switch', 'Switch')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
