# Generated by Django 5.0.3 on 2024-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_asset_name_alter_assetallocation_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ram',
        ),
        migrations.AddField(
            model_name='asset',
            name='office',
            field=models.CharField(choices=[('2007', '2007'), ('2010', '2010'), ('2013', '2013'), ('2016', '2016'), ('365', '365')], default='2007', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='office_licence',
            field=models.CharField(default='Digital', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(choices=[('win7', 'Win7'), ('win8.1', 'Win8.1'), ('win10', 'Win10'), ('win11', 'Win11')], default='win10', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_licence',
            field=models.CharField(default='Digital', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop')], default='notebook', max_length=50),
        ),
    ]
