# Generated by Django 5.0.3 on 2024-04-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_asset_ram_asset_office_asset_office_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(choices=[('2007', '2007'), ('2010', '2010'), ('2013', '2013'), ('2016', '2016'), ('365', '365')], default='2007', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office_licence',
            field=models.CharField(default='Digital', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(choices=[('win7', 'Win7'), ('win8.1', 'Win8.1'), ('win10', 'Win10'), ('win11', 'Win11')], default='win10', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_licence',
            field=models.CharField(default='Digital', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop')], default='notebook', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='employee_allocated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.employee'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='employee_returning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.employee'),
        ),
    ]
