# Generated by Django 5.0 on 2024-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_assetreturn_serial_number_alter_asset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposal',
            old_name='disposal_date',
            new_name='damage_date',
        ),
        migrations.RenameField(
            model_name='disposal',
            old_name='disposal_reason',
            new_name='damage_reason',
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
