# Generated by Django 5.0.3 on 2024-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_asset_office_alter_asset_office_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(choices=[('2007', '2007'), ('2010', '2010'), ('2013', '2013'), ('2016', '2016'), ('365', '365')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(choices=[('win7', 'Win7'), ('win8.1', 'Win8.1'), ('win10', 'Win10'), ('win11', 'Win11')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop')], max_length=50, null=True),
        ),
    ]
