# Generated by Django 5.0 on 2024-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_rename_disposal_date_disposal_damage_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disposal',
            new_name='Damaged',
        ),
    ]
