# Generated by Django 5.0.3 on 2024-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_asset_office_alter_asset_os_alter_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office_licence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os_licence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
