# Generated by Django 5.2.4 on 2025-08-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_remove_purchasereceipt_purchase_order_and_more'),
    ]

    operations = [
    ]
