# Generated by Django 5.2.4 on 2025-08-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_populate_purchaseitem_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
