# Generated by Django 5.2.4 on 2025-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_remove_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hdd_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HDD Capacity (GB/TB)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='imei_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, choices=[('i3', 'Intel Core i3'), ('i5', 'Intel Core i5'), ('i7', 'Intel Core i7'), ('i9', 'Intel Core i9'), ('ryzen3', 'AMD Ryzen 3'), ('ryzen5', 'AMD Ryzen 5'), ('ryzen7', 'AMD Ryzen 7'), ('ryzen9', 'AMD Ryzen 9'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor_cores',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Processor Cores'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, choices=[('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB'), ('64', '64GB')], max_length=10, null=True, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ssd_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SSD Capacity (GB/TB)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Storage Capacity (GB/TB)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('nvme', 'NVMe SSD'), ('hybrid', 'Hybrid (SSD+HDD)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('server', 'Server'), ('printer', 'Printer'), ('tablet', 'Tablet')], max_length=50, null=True),
        ),
    ]
