# Generated by Django 5.2.4 on 2025-08-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_asset_hdd_capacity_asset_imei_number_asset_processor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='processor_cores',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='storage_type',
        ),
    ]
