# Generated by Django 5.2.4 on 2025-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_remove_asset_processor_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='applications',
            field=models.JSONField(blank=True, default=dict, help_text='Business applications and support systems installed on this asset'),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='allocated_applications',
            field=models.JSONField(blank=True, default=dict, help_text='Applications included in this allocation'),
        ),
    ]
