# Generated by Django 5.2.4 on 2025-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_asset_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='other_applications',
            field=models.TextField(blank=True, help_text='Specify any additional software or applications not listed above', null=True, verbose_name='Other Applications Description'),
        ),
    ]
